name: Deployment pipeline

on:
  push:
    branches:
      - dev
  pull_request:

jobs:
  basic_pipeline:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: npm install
        run: npm install && cd client && npm install && cd ..
      - name: lint
        run: npm run eslint