name: Deployment pipeline

on:
  push:
    branches:
      - main
      - development

jobs:
  basic_pipeline:
    runs-on: ubuntu-18.04
    
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14'
      - name: npm install server
        run: cd server && npm install
      - name: npm install client
        run: cd client && npm install
      - name: e2e tests
        uses: cypress-io/github-action@v2
        env:
          TEST_MONGODB_URI: ${{ secrets.TEST_MONGODB_URI }}
          SECRET: 'randomsecretkey'
        with:
          browser: chrome
          headless: true
          start: docker-compose up
          wait-on: http://localhost:4000

      - name: Heroku deploy
        uses: akhileshns/heroku-deploy@v3.12.12
        # Deploy to Heroku when pushing to the main branch
        if: ${{ success() && github.ref == 'refs/heads/main' }}
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: "surveycreatorpro"
          heroku_email: ${{ secrets.EMAIL }}
          healthcheck: "https://surveycreatorpro.herokuapp.com/api/health"
          checkstring: "ok"
          rollbackonhealthcheckfailed: true
