name: Deployment pipeline

on:
  push:
    branches:
      - development

jobs:
  basic_pipeline:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: npm install
        run: npm install && cd client && npm install && cd ..
      - name: lint
        run: npm run eslint
      - name: e2e tests
        run: npm run start:test && npm run test:e2e
